export const fields = {
  firstName: {
    value: '',
    type: 'text',
    tag: 'input',
    placeholder: 'name',
    focused: false,
    errorMessage: 'must be 5 characters long',
    isValid: 'pending',
  },
  lastName: {
    value: '',
    type: 'text',
    tag: 'input',
    placeholder: 'last name',
    focused: false,
    errorMessage: 'must be 5 characters long',
    isValid: 'pending',
  },
  email: {
    value: '',
    type: 'email',
    tag: 'input',
    placeholder: 'email',
    focused: false,
    errorMessage: 'email is not valid',
    isValid: 'pending',
  },
  message: {
    value: '',
    type: '',
    tag: 'textarea',
    placeholder: 'message',
    focused: false,
    errorMessage: 'must be 5 characters long',
    isValid: 'pending',
  },
};
